CREATE TABLE IF NOT EXISTS public.be_postal_codes (
  code_postal TEXT NOT NULL,
  commune_fr  TEXT NOT NULL,
  commune_nl  TEXT NOT NULL,
  ville_fr    TEXT NOT NULL,
  province    TEXT NOT NULL,
  region      TEXT NOT NULL,
  PRIMARY KEY (code_postal, commune_fr)
);

ALTER TABLE public.be_postal_codes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "be_postal_codes_public_read"
  ON public.be_postal_codes FOR SELECT TO anon, authenticated
  USING (true);

CREATE INDEX IF NOT EXISTS idx_be_postal_code ON public.be_postal_codes(code_postal);
CREATE INDEX IF NOT EXISTS idx_be_postal_commune_fr ON public.be_postal_codes(commune_fr);
CREATE INDEX IF NOT EXISTS idx_be_postal_ville ON public.be_postal_codes(ville_fr);

ALTER TABLE public.residences ADD COLUMN IF NOT EXISTS commune TEXT;

INSERT INTO public.be_postal_codes
  (code_postal, commune_fr, commune_nl, ville_fr, province, region)
VALUES
('1000','Bruxelles','Brussel','Bruxelles','Bruxelles-Capitale','Bruxelles'),
('1020','Laeken','Laken','Bruxelles','Bruxelles-Capitale','Bruxelles'),
('1030','Schaerbeek','Schaarbeek','Schaerbeek','Bruxelles-Capitale','Bruxelles'),
('1040','Etterbeek','Etterbeek','Etterbeek','Bruxelles-Capitale','Bruxelles'),
('1050','Ixelles','Elsene','Ixelles','Bruxelles-Capitale','Bruxelles'),
('1060','Saint-Gilles','Sint-Gillis','Saint-Gilles','Bruxelles-Capitale','Bruxelles'),
('1070','Anderlecht','Anderlecht','Anderlecht','Bruxelles-Capitale','Bruxelles'),
('1080','Molenbeek-Saint-Jean','Sint-Jans-Molenbeek','Molenbeek-Saint-Jean','Bruxelles-Capitale','Bruxelles'),
('1081','Koekelberg','Koekelberg','Koekelberg','Bruxelles-Capitale','Bruxelles'),
('1082','Berchem-Sainte-Agathe','Sint-Agatha-Berchem','Berchem-Sainte-Agathe','Bruxelles-Capitale','Bruxelles'),
('1083','Ganshoren','Ganshoren','Ganshoren','Bruxelles-Capitale','Bruxelles'),
('1090','Jette','Jette','Jette','Bruxelles-Capitale','Bruxelles'),
('1120','Neder-Over-Heembeek','Neder-Over-Heembeek','Bruxelles','Bruxelles-Capitale','Bruxelles'),
('1130','Haren','Haren','Bruxelles','Bruxelles-Capitale','Bruxelles'),
('1140','Evere','Evere','Evere','Bruxelles-Capitale','Bruxelles'),
('1150','Woluwe-Saint-Pierre','Sint-Pieters-Woluwe','Woluwe-Saint-Pierre','Bruxelles-Capitale','Bruxelles'),
('1160','Auderghem','Oudergem','Auderghem','Bruxelles-Capitale','Bruxelles'),
('1170','Watermael-Boitsfort','Watermaal-Bosvoorde','Watermael-Boitsfort','Bruxelles-Capitale','Bruxelles'),
('1180','Uccle','Ukkel','Uccle','Bruxelles-Capitale','Bruxelles'),
('1190','Forest','Vorst','Forest','Bruxelles-Capitale','Bruxelles'),
('1200','Woluwe-Saint-Lambert','Sint-Lambrechts-Woluwe','Woluwe-Saint-Lambert','Bruxelles-Capitale','Bruxelles'),
('1210','Saint-Josse-ten-Noode','Sint-Joost-ten-Node','Saint-Josse-ten-Noode','Bruxelles-Capitale','Bruxelles'),
('1300','Wavre','Waver','Wavre','Brabant Wallon','Wallonie'),
('1301','Bierges','Bierges','Wavre','Brabant Wallon','Wallonie'),
('1310','La Hulpe','La Hulpe','La Hulpe','Brabant Wallon','Wallonie'),
('1315','Incourt','Incourt','Incourt','Brabant Wallon','Wallonie'),
('1320','Beauvechain','Bevekom','Beauvechain','Brabant Wallon','Wallonie'),
('1325','Chaumont-Gistoux','Chaumont-Gistoux','Chaumont-Gistoux','Brabant Wallon','Wallonie'),
('1330','Rixensart','Rixensart','Rixensart','Brabant Wallon','Wallonie'),
('1331','Rosières','Rosières','Rixensart','Brabant Wallon','Wallonie'),
('1332','Genval','Genval','Rixensart','Brabant Wallon','Wallonie'),
('1340','Ottignies','Ottignies','Ottignies-Louvain-la-Neuve','Brabant Wallon','Wallonie'),
('1341','Céroux-Mousty','Céroux-Mousty','Ottignies-Louvain-la-Neuve','Brabant Wallon','Wallonie'),
('1342','Limelette','Limelette','Ottignies-Louvain-la-Neuve','Brabant Wallon','Wallonie'),
('1348','Louvain-la-Neuve','Louvain-la-Neuve','Ottignies-Louvain-la-Neuve','Brabant Wallon','Wallonie'),
('1350','Jodoigne','Geldenaken','Jodoigne','Brabant Wallon','Wallonie'),
('1360','Perwez','Perwijs','Perwez','Brabant Wallon','Wallonie'),
('1380','Lasne','Lasne','Lasne','Brabant Wallon','Wallonie'),
('1390','Grez-Doiceau','Graven','Grez-Doiceau','Brabant Wallon','Wallonie'),
('1400','Nivelles','Nijvel','Nivelles','Brabant Wallon','Wallonie'),
('1401','Baulers','Baulers','Nivelles','Brabant Wallon','Wallonie'),
('1410','Waterloo','Waterloo','Waterloo','Brabant Wallon','Wallonie'),
('1420','Braine-l''Alleud','Eigenbrakel','Braine-l''Alleud','Brabant Wallon','Wallonie'),
('1430','Rebecq','Rebecq','Rebecq','Brabant Wallon','Wallonie'),
('1440','Wauthier-Braine','Wauthier-Braine','Braine-le-Château','Brabant Wallon','Wallonie'),
('1450','Chastre','Chastre','Chastre','Brabant Wallon','Wallonie'),
('1460','Ittre','Ittre','Ittre','Brabant Wallon','Wallonie'),
('1470','Genappe','Genappe','Genappe','Brabant Wallon','Wallonie'),
('1480','Tubize','Tubeke','Tubize','Brabant Wallon','Wallonie'),
('1490','Court-Saint-Etienne','Court-Saint-Etienne','Court-Saint-Etienne','Brabant Wallon','Wallonie'),
('6000','Charleroi','Charleroi','Charleroi','Hainaut','Wallonie'),
('6001','Marcinelle','Marcinelle','Charleroi','Hainaut','Wallonie'),
('6010','Couillet','Couillet','Charleroi','Hainaut','Wallonie'),
('6020','Dampremy','Dampremy','Charleroi','Hainaut','Wallonie'),
('6030','Marchienne-au-Pont','Marchienne-au-Pont','Charleroi','Hainaut','Wallonie'),
('6040','Jumet','Jumet','Charleroi','Hainaut','Wallonie'),
('6041','Gosselies','Gosselies','Charleroi','Hainaut','Wallonie'),
('6060','Gilly','Gilly','Charleroi','Hainaut','Wallonie'),
('6110','Montigny-le-Tilleul','Montigny-le-Tilleul','Montigny-le-Tilleul','Hainaut','Wallonie'),
('6140','Fontaine-l''Evêque','Fontaine-l''Evêque','Fontaine-l''Evêque','Hainaut','Wallonie'),
('6150','Anderlues','Anderlues','Anderlues','Hainaut','Wallonie'),
('6180','Courcelles','Courcelles','Courcelles','Hainaut','Wallonie'),
('6200','Châtelet','Châtelet','Châtelet','Hainaut','Wallonie'),
('6220','Fleurus','Fleurus','Fleurus','Hainaut','Wallonie'),
('6230','Pont-à-Celles','Pont-à-Celles','Pont-à-Celles','Hainaut','Wallonie'),
('6240','Farciennes','Farciennes','Farciennes','Hainaut','Wallonie'),
('6250','Aiseau-Presles','Aiseau-Presles','Aiseau-Presles','Hainaut','Wallonie'),
('6280','Gerpinnes','Gerpinnes','Gerpinnes','Hainaut','Wallonie'),
('7000','Mons','Bergen','Mons','Hainaut','Wallonie'),
('7012','Jemappes','Jemappes','Mons','Hainaut','Wallonie'),
('7060','Soignies','Zinnik','Soignies','Hainaut','Wallonie'),
('7080','La Louvière','La Louvière','La Louvière','Hainaut','Wallonie'),
('7090','Braine-le-Comte','''s-Gravenbrakel','Braine-le-Comte','Hainaut','Wallonie'),
('7100','La Louvière','La Louvière','La Louvière','Hainaut','Wallonie'),
('7130','Binche','Binche','Binche','Hainaut','Wallonie'),
('7170','Manage','Manage','Manage','Hainaut','Wallonie'),
('7180','Seneffe','Seneffe','Seneffe','Hainaut','Wallonie'),
('7190','Ecaussinnes','Ecaussinnes','Ecaussinnes','Hainaut','Wallonie'),
('7500','Tournai','Doornik','Tournai','Hainaut','Wallonie'),
('7600','Péruwelz','Péruwelz','Péruwelz','Hainaut','Wallonie'),
('7700','Mouscron','Moeskroen','Mouscron','Hainaut','Wallonie'),
('7730','Estaimpuis','Estaimpuis','Estaimpuis','Hainaut','Wallonie'),
('7800','Ath','Ath','Ath','Hainaut','Wallonie'),
('7850','Enghien','Edingen','Enghien','Hainaut','Wallonie'),
('7860','Lessines','Lessen','Lessines','Hainaut','Wallonie'),
('7900','Leuze-en-Hainaut','Leuze-en-Hainaut','Leuze-en-Hainaut','Hainaut','Wallonie'),
('7970','Beloeil','Beloeil','Beloeil','Hainaut','Wallonie'),
('4000','Liège','Luik','Liège','Liège','Wallonie'),
('4020','Liège','Luik','Liège','Liège','Wallonie'),
('4030','Grivegnée','Grivegnée','Liège','Liège','Wallonie'),
('4031','Angleur','Angleur','Liège','Liège','Wallonie'),
('4040','Herstal','Herstal','Herstal','Liège','Wallonie'),
('4050','Chaudfontaine','Chaudfontaine','Chaudfontaine','Liège','Wallonie'),
('4100','Seraing','Seraing','Seraing','Liège','Wallonie'),
('4120','Neupré','Neupré','Neupré','Liège','Wallonie'),
('4130','Esneux','Esneux','Esneux','Liège','Wallonie'),
('4170','Comblain-au-Pont','Comblain-au-Pont','Comblain-au-Pont','Liège','Wallonie'),
('4210','Tinlot','Tinlot','Tinlot','Liège','Wallonie'),
('4280','Hannut','Hannut','Hannut','Liège','Wallonie'),
('4300','Waremme','Borgworm','Waremme','Liège','Wallonie'),
('4400','Flémalle','Flémalle','Flémalle','Liège','Wallonie'),
('4420','Saint-Nicolas','Saint-Nicolas','Saint-Nicolas','Liège','Wallonie'),
('4430','Ans','Ans','Ans','Liège','Wallonie'),
('4460','Grâce-Hollogne','Grâce-Hollogne','Grâce-Hollogne','Liège','Wallonie'),
('4500','Huy','Hoei','Huy','Liège','Wallonie'),
('4540','Amay','Amay','Amay','Liège','Wallonie'),
('4600','Visé','Wezet','Visé','Liège','Wallonie'),
('4610','Beyne-Heusay','Beyne-Heusay','Beyne-Heusay','Liège','Wallonie'),
('4620','Fléron','Fléron','Fléron','Liège','Wallonie'),
('4630','Soumagne','Soumagne','Soumagne','Liège','Wallonie'),
('4650','Herve','Herve','Herve','Liège','Wallonie'),
('4670','Blégny','Blégny','Blégny','Liège','Wallonie'),
('4700','Eupen','Eupen','Eupen','Liège','Wallonie'),
('4720','La Calamine','Kelmis','La Calamine','Liège','Wallonie'),
('4730','Raeren','Raeren','Raeren','Liège','Wallonie'),
('4750','Butgenbach','Bütgenbach','Butgenbach','Liège','Wallonie'),
('4780','Saint-Vith','Sankt Vith','Saint-Vith','Liège','Wallonie'),
('4800','Lierneux','Lierneux','Lierneux','Liège','Wallonie'),
('4810','Theux','Theux','Theux','Liège','Wallonie'),
('4820','Dison','Dison','Dison','Liège','Wallonie'),
('4830','Limbourg','Limburg','Limbourg','Liège','Wallonie'),
('4840','Welkenraedt','Welkenraedt','Welkenraedt','Liège','Wallonie'),
('4860','Pepinster','Pepinster','Pepinster','Liège','Wallonie'),
('4880','Aubel','Aubel','Aubel','Liège','Wallonie'),
('4900','Spa','Spa','Spa','Liège','Wallonie'),
('4920','Aywaille','Aywaille','Aywaille','Liège','Wallonie'),
('4960','Malmedy','Malmedy','Malmedy','Liège','Wallonie'),
('4970','Stavelot','Stavelot','Stavelot','Liège','Wallonie'),
('4980','Trois-Ponts','Trois-Ponts','Trois-Ponts','Liège','Wallonie'),
('5000','Namur','Namen','Namur','Namur','Wallonie'),
('5002','Saint-Servais','Sint-Servaas','Namur','Namur','Wallonie'),
('5003','Saint-Marc','Saint-Marc','Namur','Namur','Wallonie'),
('5004','Bouge','Bouge','Namur','Namur','Wallonie'),
('5030','Gembloux','Gembloux','Gembloux','Namur','Wallonie'),
('5060','Sambreville','Sambreville','Sambreville','Namur','Wallonie'),
('5070','Fosses-la-Ville','Fosses-la-Ville','Fosses-la-Ville','Namur','Wallonie'),
('5100','Namur','Namen','Namur','Namur','Wallonie'),
('5140','Sombreffe','Sombreffe','Sombreffe','Namur','Wallonie'),
('5300','Andenne','Andenne','Andenne','Namur','Wallonie'),
('5310','Éghezée','Éghezée','Éghezée','Namur','Wallonie'),
('5500','Dinant','Dinant','Dinant','Namur','Wallonie'),
('5580','Rochefort','Rochefort','Rochefort','Namur','Wallonie'),
('5590','Ciney','Ciney','Ciney','Namur','Wallonie'),
('5600','Philippeville','Philippeville','Philippeville','Namur','Wallonie'),
('5620','Florennes','Florennes','Florennes','Namur','Wallonie'),
('5650','Walcourt','Walcourt','Walcourt','Namur','Wallonie'),
('5660','Couvin','Couvin','Couvin','Namur','Wallonie'),
('6600','Bastogne','Bastenaken','Bastogne','Luxembourg','Wallonie'),
('6700','Arlon','Aarlen','Arlon','Luxembourg','Wallonie'),
('6720','Habay','Habay','Habay','Luxembourg','Wallonie'),
('6760','Virton','Virton','Virton','Luxembourg','Wallonie'),
('6800','Libramont-Chevigny','Libramont-Chevigny','Libramont-Chevigny','Luxembourg','Wallonie'),
('6820','Florenville','Florenville','Florenville','Luxembourg','Wallonie'),
('6830','Bouillon','Bouillon','Bouillon','Luxembourg','Wallonie'),
('6840','Neufchâteau','Neufchâteau','Neufchâteau','Luxembourg','Wallonie'),
('6900','Marche-en-Famenne','Marche-en-Famenne','Marche-en-Famenne','Luxembourg','Wallonie'),
('6940','Durbuy','Durbuy','Durbuy','Luxembourg','Wallonie'),
('6980','La Roche-en-Ardenne','La Roche-en-Ardenne','La Roche-en-Ardenne','Luxembourg','Wallonie'),
('1500','Halle','Halle','Halle','Brabant Flamand','Flandre'),
('1560','Hoeilaart','Hoeilaart','Hoeilaart','Brabant Flamand','Flandre'),
('1600','Sint-Pieters-Leeuw','Sint-Pieters-Leeuw','Sint-Pieters-Leeuw','Brabant Flamand','Flandre'),
('1640','Rhode-Saint-Genèse','Sint-Genesius-Rode','Rhode-Saint-Genèse','Brabant Flamand','Flandre'),
('1650','Beersel','Beersel','Beersel','Brabant Flamand','Flandre'),
('1700','Dilbeek','Dilbeek','Dilbeek','Brabant Flamand','Flandre'),
('1730','Asse','Asse','Asse','Brabant Flamand','Flandre'),
('1740','Ternat','Ternat','Ternat','Brabant Flamand','Flandre'),
('1800','Vilvoorde','Vilvorde','Vilvoorde','Brabant Flamand','Flandre'),
('1820','Steenokkerzeel','Steenokkerzeel','Steenokkerzeel','Brabant Flamand','Flandre'),
('1830','Machelen','Machelen','Machelen','Brabant Flamand','Flandre'),
('1840','Londerzeel','Londerzeel','Londerzeel','Brabant Flamand','Flandre'),
('1850','Grimbergen','Grimbergen','Grimbergen','Brabant Flamand','Flandre'),
('1860','Meise','Meise','Meise','Brabant Flamand','Flandre'),
('1880','Kapelle-op-den-Bos','Kapelle-op-den-Bos','Kapelle-op-den-Bos','Brabant Flamand','Flandre'),
('1900','Overijse','Overijse','Overijse','Brabant Flamand','Flandre'),
('1930','Zaventem','Zaventem','Zaventem','Brabant Flamand','Flandre'),
('1950','Kraainem','Kraainem','Kraainem','Brabant Flamand','Flandre'),
('1980','Zemst','Zemst','Zemst','Brabant Flamand','Flandre'),
('3000','Louvain','Leuven','Louvain','Brabant Flamand','Flandre'),
('3010','Kessel-Lo','Kessel-Lo','Louvain','Brabant Flamand','Flandre'),
('3020','Herent','Herent','Herent','Brabant Flamand','Flandre'),
('3040','Huldenberg','Huldenberg','Huldenberg','Brabant Flamand','Flandre'),
('3050','Oud-Heverlee','Oud-Heverlee','Oud-Heverlee','Brabant Flamand','Flandre'),
('3060','Bertem','Bertem','Bertem','Brabant Flamand','Flandre'),
('3070','Kortenberg','Kortenberg','Kortenberg','Brabant Flamand','Flandre'),
('3080','Tervuren','Tervuren','Tervuren','Brabant Flamand','Flandre'),
('3200','Aarschot','Aarschot','Aarschot','Brabant Flamand','Flandre'),
('3290','Diest','Diest','Diest','Brabant Flamand','Flandre'),
('3300','Tienen','Tirlemont','Tienen','Brabant Flamand','Flandre'),
('3400','Landen','Landen','Landen','Brabant Flamand','Flandre'),
('2000','Anvers','Antwerpen','Anvers','Anvers','Flandre'),
('2018','Anvers','Antwerpen','Anvers','Anvers','Flandre'),
('2020','Anvers','Antwerpen','Anvers','Anvers','Flandre'),
('2030','Anvers','Antwerpen','Anvers','Anvers','Flandre'),
('2040','Anvers','Antwerpen','Anvers','Anvers','Flandre'),
('2050','Anvers','Antwerpen','Anvers','Anvers','Flandre'),
('2060','Anvers','Antwerpen','Anvers','Anvers','Flandre'),
('2070','Zwijndrecht','Zwijndrecht','Zwijndrecht','Anvers','Flandre'),
('2100','Deurne','Deurne','Anvers','Anvers','Flandre'),
('2110','Wijnegem','Wijnegem','Wijnegem','Anvers','Flandre'),
('2140','Borgerhout','Borgerhout','Anvers','Anvers','Flandre'),
('2150','Borsbeek','Borsbeek','Borsbeek','Anvers','Flandre'),
('2160','Wommelgem','Wommelgem','Wommelgem','Anvers','Flandre'),
('2170','Merksem','Merksem','Anvers','Anvers','Flandre'),
('2180','Ekeren','Ekeren','Anvers','Anvers','Flandre'),
('2200','Herentals','Herentals','Herentals','Anvers','Flandre'),
('2230','Herselt','Herselt','Herselt','Anvers','Flandre'),
('2240','Zandhoven','Zandhoven','Zandhoven','Anvers','Flandre'),
('2260','Westerlo','Westerlo','Westerlo','Anvers','Flandre'),
('2270','Herenthout','Herenthout','Herenthout','Anvers','Flandre'),
('2280','Grobbendonk','Grobbendonk','Grobbendonk','Anvers','Flandre'),
('2290','Vorselaar','Vorselaar','Vorselaar','Anvers','Flandre'),
('2300','Turnhout','Turnhout','Turnhout','Anvers','Flandre'),
('2320','Hoogstraten','Hoogstraten','Hoogstraten','Anvers','Flandre'),
('2330','Merksplas','Merksplas','Merksplas','Anvers','Flandre'),
('2340','Beerse','Beerse','Beerse','Anvers','Flandre'),
('2350','Vosselaar','Vosselaar','Vosselaar','Anvers','Flandre'),
('2360','Oud-Turnhout','Oud-Turnhout','Oud-Turnhout','Anvers','Flandre'),
('2370','Arendonk','Arendonk','Arendonk','Anvers','Flandre'),
('2380','Ravels','Ravels','Ravels','Anvers','Flandre'),
('2390','Malle','Malle','Malle','Anvers','Flandre'),
('2400','Mol','Mol','Mol','Anvers','Flandre'),
('2430','Laakdal','Laakdal','Laakdal','Anvers','Flandre'),
('2440','Geel','Geel','Geel','Anvers','Flandre'),
('2450','Meerhout','Meerhout','Meerhout','Anvers','Flandre'),
('2460','Kasterlee','Kasterlee','Kasterlee','Anvers','Flandre'),
('2470','Retie','Retie','Retie','Anvers','Flandre'),
('2480','Dessel','Dessel','Dessel','Anvers','Flandre'),
('2490','Balen','Balen','Balen','Anvers','Flandre'),
('2500','Lier','Lier','Lier','Anvers','Flandre'),
('2520','Ranst','Ranst','Ranst','Anvers','Flandre'),
('2530','Boechout','Boechout','Boechout','Anvers','Flandre'),
('2540','Hove','Hove','Hove','Anvers','Flandre'),
('2547','Lint','Lint','Lint','Anvers','Flandre'),
('2550','Kontich','Kontich','Kontich','Anvers','Flandre'),
('2560','Nijlen','Nijlen','Nijlen','Anvers','Flandre'),
('2570','Duffel','Duffel','Duffel','Anvers','Flandre'),
('2580','Putte','Putte','Putte','Anvers','Flandre'),
('2590','Berlaar','Berlaar','Berlaar','Anvers','Flandre'),
('2600','Berchem','Berchem','Anvers','Anvers','Flandre'),
('2610','Wilrijk','Wilrijk','Anvers','Anvers','Flandre'),
('2620','Hemiksem','Hemiksem','Hemiksem','Anvers','Flandre'),
('2627','Schelle','Schelle','Schelle','Anvers','Flandre'),
('2630','Aartselaar','Aartselaar','Aartselaar','Anvers','Flandre'),
('2640','Mortsel','Mortsel','Mortsel','Anvers','Flandre'),
('2650','Edegem','Edegem','Edegem','Anvers','Flandre'),
('2660','Hoboken','Hoboken','Anvers','Anvers','Flandre'),
('2800','Malines','Mechelen','Malines','Anvers','Flandre'),
('2811','Leest','Leest','Malines','Anvers','Flandre'),
('2812','Muizen','Muizen','Malines','Anvers','Flandre'),
('2820','Bonheiden','Bonheiden','Bonheiden','Anvers','Flandre'),
('2830','Willebroek','Willebroek','Willebroek','Anvers','Flandre'),
('2840','Rumst','Rumst','Rumst','Anvers','Flandre'),
('2845','Niel','Niel','Niel','Anvers','Flandre'),
('2850','Boom','Boom','Boom','Anvers','Flandre'),
('2860','Sint-Katelijne-Waver','Sint-Katelijne-Waver','Sint-Katelijne-Waver','Anvers','Flandre'),
('2870','Puurs-Sint-Amands','Puurs-Sint-Amands','Puurs-Sint-Amands','Anvers','Flandre'),
('2880','Bornem','Bornem','Bornem','Anvers','Flandre'),
('2890','Lippelo','Lippelo','Puurs-Sint-Amands','Anvers','Flandre'),
('2900','Schoten','Schoten','Schoten','Anvers','Flandre'),
('2910','Essen','Essen','Essen','Anvers','Flandre'),
('2920','Kalmthout','Kalmthout','Kalmthout','Anvers','Flandre'),
('2930','Brasschaat','Brasschaat','Brasschaat','Anvers','Flandre'),
('2940','Stabroek','Stabroek','Stabroek','Anvers','Flandre'),
('2950','Kapellen','Kapellen','Kapellen','Anvers','Flandre'),
('2960','Brecht','Brecht','Brecht','Anvers','Flandre'),
('2970','Schilde','Schilde','Schilde','Anvers','Flandre'),
('2980','Zoersel','Zoersel','Zoersel','Anvers','Flandre'),
('2990','Wuustwezel','Wuustwezel','Wuustwezel','Anvers','Flandre'),
('9000','Gand','Gent','Gand','Flandre Orientale','Flandre'),
('9030','Mariakerke','Mariakerke','Gand','Flandre Orientale','Flandre'),
('9031','Drongen','Drongen','Gand','Flandre Orientale','Flandre'),
('9032','Wondelgem','Wondelgem','Gand','Flandre Orientale','Flandre'),
('9040','Sint-Amandsberg','Sint-Amandsberg','Gand','Flandre Orientale','Flandre'),
('9041','Oostakker','Oostakker','Gand','Flandre Orientale','Flandre'),
('9042','Desteldonk','Desteldonk','Gand','Flandre Orientale','Flandre'),
('9050','Gentbrugge','Gentbrugge','Gand','Flandre Orientale','Flandre'),
('9051','Sint-Denijs-Westrem','Sint-Denijs-Westrem','Gand','Flandre Orientale','Flandre'),
('9052','Zwijnaarde','Zwijnaarde','Gand','Flandre Orientale','Flandre'),
('9060','Zelzate','Zelzate','Zelzate','Flandre Orientale','Flandre'),
('9070','Destelbergen','Destelbergen','Destelbergen','Flandre Orientale','Flandre'),
('9080','Lochristi','Lochristi','Lochristi','Flandre Orientale','Flandre'),
('9090','Melle','Melle','Melle','Flandre Orientale','Flandre'),
('9100','Sint-Niklaas','Sint-Niklaas','Sint-Niklaas','Flandre Orientale','Flandre'),
('9111','Belsele','Belsele','Sint-Niklaas','Flandre Orientale','Flandre'),
('9112','Sinaai','Sinaai','Sint-Niklaas','Flandre Orientale','Flandre'),
('9120','Beveren','Beveren','Beveren','Flandre Orientale','Flandre'),
('9130','Verrebroek','Verrebroek','Beveren','Flandre Orientale','Flandre'),
('9140','Temse','Temse','Temse','Flandre Orientale','Flandre'),
('9150','Kruibeke','Kruibeke','Kruibeke','Flandre Orientale','Flandre'),
('9160','Lokeren','Lokeren','Lokeren','Flandre Orientale','Flandre'),
('9170','Sint-Gillis-Waas','Sint-Gillis-Waas','Sint-Gillis-Waas','Flandre Orientale','Flandre'),
('9180','Moerbeke','Moerbeke','Moerbeke','Flandre Orientale','Flandre'),
('9185','Wachtebeke','Wachtebeke','Wachtebeke','Flandre Orientale','Flandre'),
('9190','Stekene','Stekene','Stekene','Flandre Orientale','Flandre'),
('9200','Dendermonde','Dendermonde','Dendermonde','Flandre Orientale','Flandre'),
('9220','Hamme','Hamme','Hamme','Flandre Orientale','Flandre'),
('9230','Wetteren','Wetteren','Wetteren','Flandre Orientale','Flandre'),
('9240','Zele','Zele','Zele','Flandre Orientale','Flandre'),
('9250','Waasmunster','Waasmunster','Waasmunster','Flandre Orientale','Flandre'),
('9260','Wichelen','Wichelen','Wichelen','Flandre Orientale','Flandre'),
('9270','Laarne','Laarne','Laarne','Flandre Orientale','Flandre'),
('9280','Lebbeke','Lebbeke','Lebbeke','Flandre Orientale','Flandre'),
('9290','Berlare','Berlare','Berlare','Flandre Orientale','Flandre'),
('9300','Aalst','Alost','Aalst','Flandre Orientale','Flandre'),
('9308','Hofstade','Hofstade','Aalst','Flandre Orientale','Flandre'),
('9310','Baardegem','Baardegem','Aalst','Flandre Orientale','Flandre'),
('9320','Erembodegem','Erembodegem','Aalst','Flandre Orientale','Flandre'),
('9340','Lede','Lede','Lede','Flandre Orientale','Flandre'),
('9400','Ninove','Ninove','Ninove','Flandre Orientale','Flandre'),
('9420','Erpe-Mere','Erpe-Mere','Erpe-Mere','Flandre Orientale','Flandre'),
('9450','Haaltert','Haaltert','Haaltert','Flandre Orientale','Flandre'),
('9470','Denderleeuw','Denderleeuw','Denderleeuw','Flandre Orientale','Flandre'),
('9500','Geraardsbergen','Geraardsbergen','Geraardsbergen','Flandre Orientale','Flandre'),
('9550','Herzele','Herzele','Herzele','Flandre Orientale','Flandre'),
('9600','Ronse','Renaix','Ronse','Flandre Orientale','Flandre'),
('9620','Zottegem','Zottegem','Zottegem','Flandre Orientale','Flandre'),
('9630','Brakel','Brakel','Brakel','Flandre Orientale','Flandre'),
('9660','Brakel','Brakel','Brakel','Flandre Orientale','Flandre'),
('9700','Audenarde','Oudenaarde','Audenarde','Flandre Orientale','Flandre'),
('9750','Kruisem','Kruisem','Kruisem','Flandre Orientale','Flandre'),
('9770','Kruishoutem','Kruishoutem','Kruisem','Flandre Orientale','Flandre'),
('9800','Deinze','Deinze','Deinze','Flandre Orientale','Flandre'),
('9820','Merelbeke','Merelbeke','Merelbeke','Flandre Orientale','Flandre'),
('9830','Sint-Martens-Latem','Sint-Martens-Latem','Sint-Martens-Latem','Flandre Orientale','Flandre'),
('9840','De Pinte','De Pinte','De Pinte','Flandre Orientale','Flandre'),
('9850','Nevele','Nevele','Deinze','Flandre Orientale','Flandre'),
('9860','Oosterzele','Oosterzele','Oosterzele','Flandre Orientale','Flandre'),
('9870','Zulte','Zulte','Zulte','Flandre Orientale','Flandre'),
('9880','Aalter','Aalter','Aalter','Flandre Orientale','Flandre'),
('9890','Gavere','Gavere','Gavere','Flandre Orientale','Flandre'),
('9900','Eeklo','Eeklo','Eeklo','Flandre Orientale','Flandre'),
('9910','Knesselare','Knesselare','Aalter','Flandre Orientale','Flandre'),
('9920','Lovendegem','Lovendegem','Lievegem','Flandre Orientale','Flandre'),
('9930','Zomergem','Zomergem','Lievegem','Flandre Orientale','Flandre'),
('9940','Evergem','Evergem','Evergem','Flandre Orientale','Flandre'),
('9950','Waarschoot','Waarschoot','Lievegem','Flandre Orientale','Flandre'),
('9960','Assenede','Assenede','Assenede','Flandre Orientale','Flandre'),
('9968','Bassevelde','Bassevelde','Assenede','Flandre Orientale','Flandre'),
('9970','Kaprijke','Kaprijke','Kaprijke','Flandre Orientale','Flandre'),
('9980','Sint-Laureins','Sint-Laureins','Sint-Laureins','Flandre Orientale','Flandre'),
('9988','Watervliet','Watervliet','Sint-Laureins','Flandre Orientale','Flandre'),
('9990','Maldegem','Maldegem','Maldegem','Flandre Orientale','Flandre'),
('8000','Bruges','Brugge','Bruges','Flandre Occidentale','Flandre'),
('8020','Oostkamp','Oostkamp','Oostkamp','Flandre Occidentale','Flandre'),
('8200','Sint-Andries','Sint-Andries','Bruges','Flandre Occidentale','Flandre'),
('8210','Zedelgem','Zedelgem','Zedelgem','Flandre Occidentale','Flandre'),
('8300','Knokke-Heist','Knokke-Heist','Knokke-Heist','Flandre Occidentale','Flandre'),
('8301','Heist-aan-Zee','Heist-aan-Zee','Knokke-Heist','Flandre Occidentale','Flandre'),
('8310','Assebroek','Assebroek','Bruges','Flandre Occidentale','Flandre'),
('8370','Blankenberge','Blankenberge','Blankenberge','Flandre Occidentale','Flandre'),
('8380','Zeebrugge','Zeebrugge','Bruges','Flandre Occidentale','Flandre'),
('8400','Ostende','Oostende','Ostende','Flandre Occidentale','Flandre'),
('8420','De Haan','De Haan','De Haan','Flandre Occidentale','Flandre'),
('8430','Middelkerke','Middelkerke','Middelkerke','Flandre Occidentale','Flandre'),
('8440','Westende','Westende','Middelkerke','Flandre Occidentale','Flandre'),
('8450','Bredene','Bredene','Bredene','Flandre Occidentale','Flandre'),
('8460','Oudenburg','Oudenburg','Oudenburg','Flandre Occidentale','Flandre'),
('8470','Gistel','Gistel','Gistel','Flandre Occidentale','Flandre'),
('8480','Ichtegem','Ichtegem','Ichtegem','Flandre Occidentale','Flandre'),
('8490','Varsenare','Varsenare','Jabbeke','Flandre Occidentale','Flandre'),
('8500','Courtrai','Kortrijk','Courtrai','Flandre Occidentale','Flandre'),
('8510','Marke','Marke','Courtrai','Flandre Occidentale','Flandre'),
('8520','Kuurne','Kuurne','Kuurne','Flandre Occidentale','Flandre'),
('8530','Harelbeke','Harelbeke','Harelbeke','Flandre Occidentale','Flandre'),
('8540','Deerlijk','Deerlijk','Deerlijk','Flandre Occidentale','Flandre'),
('8550','Zwevegem','Zwevegem','Zwevegem','Flandre Occidentale','Flandre'),
('8560','Wevelgem','Wevelgem','Wevelgem','Flandre Occidentale','Flandre'),
('8570','Anzegem','Anzegem','Anzegem','Flandre Occidentale','Flandre'),
('8580','Avelgem','Avelgem','Avelgem','Flandre Occidentale','Flandre'),
('8587','Spiere-Helkijn','Spiere-Helkijn','Spiere-Helkijn','Flandre Occidentale','Flandre'),
('8600','Diksmuide','Diksmuide','Diksmuide','Flandre Occidentale','Flandre'),
('8610','Kortemark','Kortemark','Kortemark','Flandre Occidentale','Flandre'),
('8620','Nieuwpoort','Nieuwpoort','Nieuwpoort','Flandre Occidentale','Flandre'),
('8630','Veurne','Veurne','Veurne','Flandre Occidentale','Flandre'),
('8640','Woumen','Woumen','Diksmuide','Flandre Occidentale','Flandre'),
('8647','Lo-Reninge','Lo-Reninge','Lo-Reninge','Flandre Occidentale','Flandre'),
('8650','Houthulst','Houthulst','Houthulst','Flandre Occidentale','Flandre'),
('8660','De Panne','De Panne','De Panne','Flandre Occidentale','Flandre'),
('8670','Koksijde','Koksijde','Koksijde','Flandre Occidentale','Flandre'),
('8680','Koekelare','Koekelare','Koekelare','Flandre Occidentale','Flandre'),
('8690','Alveringem','Alveringem','Alveringem','Flandre Occidentale','Flandre'),
('8700','Tielt','Tielt','Tielt','Flandre Occidentale','Flandre'),
('8710','Wielsbeke','Wielsbeke','Wielsbeke','Flandre Occidentale','Flandre'),
('8720','Dentergem','Dentergem','Dentergem','Flandre Occidentale','Flandre'),
('8730','Beernem','Beernem','Beernem','Flandre Occidentale','Flandre'),
('8740','Pittem','Pittem','Pittem','Flandre Occidentale','Flandre'),
('8750','Wingene','Wingene','Wingene','Flandre Occidentale','Flandre'),
('8760','Meulebeke','Meulebeke','Meulebeke','Flandre Occidentale','Flandre'),
('8770','Ingelmunster','Ingelmunster','Ingelmunster','Flandre Occidentale','Flandre'),
('8780','Oostrozebeke','Oostrozebeke','Oostrozebeke','Flandre Occidentale','Flandre'),
('8790','Waregem','Waregem','Waregem','Flandre Occidentale','Flandre'),
('8800','Roeselare','Roeselare','Roeselare','Flandre Occidentale','Flandre'),
('8810','Lichtervelde','Lichtervelde','Lichtervelde','Flandre Occidentale','Flandre'),
('8820','Torhout','Torhout','Torhout','Flandre Occidentale','Flandre'),
('8830','Hooglede','Hooglede','Hooglede','Flandre Occidentale','Flandre'),
('8840','Staden','Staden','Staden','Flandre Occidentale','Flandre'),
('8850','Ardooie','Ardooie','Ardooie','Flandre Occidentale','Flandre'),
('8860','Lendelede','Lendelede','Lendelede','Flandre Occidentale','Flandre'),
('8870','Izegem','Izegem','Izegem','Flandre Occidentale','Flandre'),
('8880','Ledegem','Ledegem','Ledegem','Flandre Occidentale','Flandre'),
('8890','Moorslede','Moorslede','Moorslede','Flandre Occidentale','Flandre'),
('8900','Ypres','Ieper','Ypres','Flandre Occidentale','Flandre'),
('8906','Elverdinge','Elverdinge','Ypres','Flandre Occidentale','Flandre'),
('8908','Vlamertinge','Vlamertinge','Ypres','Flandre Occidentale','Flandre'),
('8920','Langemark-Poelkapelle','Langemark-Poelkapelle','Langemark-Poelkapelle','Flandre Occidentale','Flandre'),
('8930','Mesen','Messines','Mesen','Flandre Occidentale','Flandre'),
('8940','Wervik','Wervik','Wervik','Flandre Occidentale','Flandre'),
('8950','Nieuwkerke','Nieuwkerke','Heuvelland','Flandre Occidentale','Flandre'),
('8954','Wulvergem','Wulvergem','Heuvelland','Flandre Occidentale','Flandre'),
('8956','Kemmel','Kemmel','Heuvelland','Flandre Occidentale','Flandre'),
('8957','Mesen','Messines','Mesen','Flandre Occidentale','Flandre'),
('8958','Loker','Loker','Heuvelland','Flandre Occidentale','Flandre'),
('8970','Poperinge','Poperinge','Poperinge','Flandre Occidentale','Flandre'),
('8972','Roesbrugge-Haringe','Roesbrugge-Haringe','Poperinge','Flandre Occidentale','Flandre'),
('8978','Watou','Watou','Poperinge','Flandre Occidentale','Flandre'),
('8980','Zonnebeke','Zonnebeke','Zonnebeke','Flandre Occidentale','Flandre'),
('3500','Hasselt','Hasselt','Hasselt','Limbourg','Flandre'),
('3510','Kermt','Kermt','Hasselt','Limbourg','Flandre'),
('3520','Zonhoven','Zonhoven','Zonhoven','Limbourg','Flandre'),
('3530','Houthalen-Helchteren','Houthalen-Helchteren','Houthalen-Helchteren','Limbourg','Flandre'),
('3540','Herk-de-Stad','Herk-de-Stad','Herk-de-Stad','Limbourg','Flandre'),
('3545','Halen','Halen','Halen','Limbourg','Flandre'),
('3550','Heusden-Zolder','Heusden-Zolder','Heusden-Zolder','Limbourg','Flandre'),
('3560','Lummen','Lummen','Lummen','Limbourg','Flandre'),
('3570','Alken','Alken','Alken','Limbourg','Flandre'),
('3580','Beringen','Beringen','Beringen','Limbourg','Flandre'),
('3582','Koersel','Koersel','Beringen','Limbourg','Flandre'),
('3583','Beverlo','Beverlo','Beringen','Limbourg','Flandre'),
('3590','Diepenbeek','Diepenbeek','Diepenbeek','Limbourg','Flandre'),
('3600','Genk','Genk','Genk','Limbourg','Flandre'),
('3620','Lanaken','Lanaken','Lanaken','Limbourg','Flandre'),
('3621','Rekem','Rekem','Lanaken','Limbourg','Flandre'),
('3630','Maasmechelen','Maasmechelen','Maasmechelen','Limbourg','Flandre'),
('3640','Kinrooi','Kinrooi','Kinrooi','Limbourg','Flandre'),
('3650','Dilsen-Stokkem','Dilsen-Stokkem','Dilsen-Stokkem','Limbourg','Flandre'),
('3660','Opglabbeek','Opglabbeek','As','Limbourg','Flandre'),
('3665','As','As','As','Limbourg','Flandre'),
('3668','Niel-bij-As','Niel-bij-As','As','Limbourg','Flandre'),
('3670','Oudsbergen','Oudsbergen','Oudsbergen','Limbourg','Flandre'),
('3680','Maaseik','Maaseik','Maaseik','Limbourg','Flandre'),
('3690','Zutendaal','Zutendaal','Zutendaal','Limbourg','Flandre'),
('3700','Tongres','Tongeren','Tongres','Limbourg','Flandre'),
('3717','Herstappe','Herstappe','Herstappe','Limbourg','Flandre'),
('3720','Kortessem','Kortessem','Kortessem','Limbourg','Flandre'),
('3721','Kortessem','Kortessem','Kortessem','Limbourg','Flandre'),
('3722','Wintershoven','Wintershoven','Kortessem','Limbourg','Flandre'),
('3723','Guigoven','Guigoven','Kortessem','Limbourg','Flandre'),
('3724','Vliermaalroot','Vliermaalroot','Kortessem','Limbourg','Flandre'),
('3730','Hoeselt','Hoeselt','Hoeselt','Limbourg','Flandre'),
('3740','Bilzen','Bilzen','Bilzen','Limbourg','Flandre'),
('3742','Martenslinde','Martenslinde','Bilzen','Limbourg','Flandre'),
('3746','Hoelbeek','Hoelbeek','Bilzen','Limbourg','Flandre'),
('3770','Riemst','Riemst','Riemst','Limbourg','Flandre'),
('3800','Sint-Truiden','Saint-Trond','Sint-Truiden','Limbourg','Flandre'),
('3803','Kerkom-bij-Sint-Truiden','Kerkom-bij-Sint-Truiden','Sint-Truiden','Limbourg','Flandre'),
('3806','Velm','Velm','Sint-Truiden','Limbourg','Flandre'),
('3830','Wellen','Wellen','Wellen','Limbourg','Flandre'),
('3840','Borgloon','Borgloon','Borgloon','Limbourg','Flandre'),
('3850','Nieuwerkerken','Nieuwerkerken','Nieuwerkerken','Limbourg','Flandre'),
('3870','Heers','Heers','Heers','Limbourg','Flandre'),
('3890','Gingelom','Gingelom','Gingelom','Limbourg','Flandre'),
('3900','Overpelt','Overpelt','Pelt','Limbourg','Flandre'),
('3910','Neerpelt','Neerpelt','Pelt','Limbourg','Flandre'),
('3920','Lommel','Lommel','Lommel','Limbourg','Flandre'),
('3930','Hamont-Achel','Hamont-Achel','Hamont-Achel','Limbourg','Flandre'),
('3940','Hechtel-Eksel','Hechtel-Eksel','Hechtel-Eksel','Limbourg','Flandre'),
('3945','Ham','Ham','Ham','Limbourg','Flandre'),
('3950','Bocholt','Bocholt','Bocholt','Limbourg','Flandre'),
('3960','Bree','Bree','Bree','Limbourg','Flandre'),
('3970','Leopoldsburg','Leopoldsburg','Leopoldsburg','Limbourg','Flandre'),
('3980','Tessenderlo','Tessenderlo','Tessenderlo','Limbourg','Flandre'),
('3990','Peer','Peer','Peer','Limbourg','Flandre')
ON CONFLICT DO NOTHING;